Try to avoid error with system ruby
https://github.com/ruby/snap.ruby/runs/3934171075?check_suite_focus=true#step:4:1861
```
Generating RDoc documentation
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:50:in `<class:Specification>': undefined method `rubyforge_project=' for class `Gem::Specification' (NameError)
	from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:49:in `<top (required)>'
	from /home/runner/work/snap.ruby/snap.ruby/parts/ruby/build/lib/rubygems.rb:1348:in `require'
	from /home/runner/work/snap.ruby/snap.ruby/parts/ruby/build/lib/rubygems.rb:1348:in `<top (required)>'
	from /home/runner/work/snap.ruby/snap.ruby/parts/ruby/build/lib/rdoc/rdoc.rb:554:in `require'
	from /home/runner/work/snap.ruby/snap.ruby/parts/ruby/build/lib/rdoc/rdoc.rb:554:in `<top (required)>'
	from ./libexec/rdoc:16:in `require'
	from ./libexec/rdoc:16:in `<main>'
```